### ISSUE TITLE
I don't know how i can contact you!

### ISSUE THREAD

**Issue by Gurkengewuerz** [nikkimas/LAN-Party-Utilities#1]
GER:
Hey, ich weiß nicht wie ich dich kontaktieren konnte, also habe ich das mal auf eine umständliche Art und weise gemacht. Bei dem Terraria Server Mod hast du ein Bild von Putty gepostet. Ist das die neuste version oder Terraria 1.2? Habe das ganze auf meinem Pi ausprobiert und es hat nicht Funktioniert.

ENG:
Hey, I do not know how I could contact you, so I've done time in a roundabout way. In the Mod Terraria server you have an image of Putty posted. Is this the latest version or Terraria 1.2? Have all of my Pi tried and it has not worked.

**Comment by nikkimas** [comment]
gute art mich zu kontaktieren :'D. Nee is noch die alter version, ich versuche grade nen 1.3 server zu starten

**Comment by Gurkengewuerz** [comment]
Okay, wenn du einen Erfolg hast würde ich mich freuen wenn du mir Bescheid geben könntest ;-) könntest Mich dann gerne eine Email schreiben, steht auf meinem Profil. 

Danke schonmal im voraus :-)

**Comment by nikkimas** [comment]
soo, geb das mal in einem **leerem(!)** Ordner ein:
`wget http://macoga.de/Downloads/tdsm-script.sh && chmod +x tdsm-script.sh && ./tdsm-script.sh`

Hoffe mal das funktioniert auf nem Pi. Habs nur auf Debian 8 getestet ^^

**Comment by nikkimas** [comment]
Sag dann mal, obs geklappt hat oder nicht. Würde mich interessieren ^^

**Comment by Gurkengewuerz** [comment]
Schaue ich mir morgen an. Vielen Dank schonmal. Kann dann auch vom RP1 und RP2 berichten

**Comment by Gurkengewuerz** [comment]
Negativ, Bei mir scheitert es immer an der World Generation

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.World.Generation.GenerationProgress.set_Message (System.String value) [0x00000] in <filename unknown>:0
  at Terraria.WorldGen+<>c__DisplayClass94.<generateWorld>b__10 (Terraria.World.Generation.GenerationProgress progress) [0x00000] in <filename unknown>:0
  at Terraria.GameContent.Generation.PassLegacy.Apply (Terraria.World.Generation.GenerationProgress progress) [0x00000] in <filename unknown>:0
  at Terraria.World.Generation.WorldGenerator.GenerateWorld (Terraria.World.Generation.GenerationProgress progress) [0x00000] in <filename unknown>:0
  at Terraria.WorldGen.generateWorld (Int32 seed, Terraria.World.Generation.GenerationProgress customProgressObject) [0x00000] in <filename unknown>:0
  at Terraria.WorldGen.worldGenCallBack (System.Object threadContext) [0x00000] in <filename unknown>:0

---

root@niklaspi:/home/pi/tdsm/Binaries# mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4+rpi1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
root@niklaspi:/home/pi/tdsm/Binaries#

---

Raspberry Pi 2 B, 1 G RAM, A 900MHz quad-core ARM Cortex-A7 CPU, Neuste Raspberry Debian Version

**Comment by nikkimas** [comment]
mach mal 
`apt-get -y update && apt-get -y upgrade`
als root

**Comment by nikkimas** [comment]
gibt es eine Möglichkeit, dich besser zu kontaktieren? Steam o.ä.
Hier is mein Steam link, falls du es auch besser finden würdest ^^
http://steamcommunity.com/id/MrDj201/
